import { useCallback, useEffect, useRef, useState } from "react";
import { getForecast, getTowns, RequestError } from "./lib/api";
import { demoForecast, demoTowns } from "./lib/demo";
import { nextDays, taipeiToday, untilNextTaipeiMidnight } from "./lib/date";
import type { Forecast, Town } from "./lib/domain";

const fullUrl = import.meta.env.VITE_TWP_FULL_PLANNER_URL || "https://twpfe5ce0.z23.web.core.windows.net/";
const compactUrl = import.meta.env.BASE_URL;

function Selector({ town, towns, disabled, onChange }: { town: string; towns: Town[]; disabled: boolean; onChange: (code: string) => void }) {
  return <section className="controls" aria-label="預報選擇"><label htmlFor="town">縣市／鄉鎮</label><select id="town" value={town} disabled={disabled || !towns.length} onChange={event => onChange(event.target.value)}><option value="">選擇鄉鎮</option>{towns.map(item => <option key={item.code} value={item.code}>{item.city} {item.name}</option>)}</select></section>;
}

export default function App() {
  const params = new URLSearchParams(location.search); const forced = params.get("demo") === "1"; const compact = params.get("view") === "compact";
  const [towns, setTowns] = useState<Town[]>(forced ? demoTowns : []); const [town, setTown] = useState(forced ? demoTowns[0].code : ""); const [data, setData] = useState<Forecast | null>(forced ? demoForecast() : null); const [mode, setMode] = useState(forced ? "demo" : "idle"); const [message, setMessage] = useState(""); const controller = useRef<AbortController>(); const seq = useRef(0);
  const load = useCallback(async (code: string, demo = false) => { controller.current?.abort(); const id = ++seq.current; if (demo) { const item = demoTowns.find(value => value.code === code) || demoTowns[0]; setTown(item.code); setData(demoForecast(item)); setMode("demo"); setMessage(""); return; } const current = new AbortController(); controller.current = current; setMode("loading"); setMessage(""); const cold = window.setTimeout(() => { if (id === seq.current) setMode("cold"); }, 2500); try { const result = await getForecast(code, taipeiToday(), current.signal); if (id !== seq.current) return; if (!result.forecast.days.some(value => value.date === result.forecast.target_date)) { setData(null); setMode("empty"); } else { setData(result); setMode("success"); } } catch (error) { if (id === seq.current) { setData(null); setMode("error"); setMessage(error instanceof RequestError ? error.message : "服務暫時無法回應"); } } finally { window.clearTimeout(cold); } }, []);
  useEffect(() => { if (forced) return; const current = new AbortController(); getTowns(current.signal).then(list => { setTowns(list); setTown(list[0]?.code || ""); if (list[0]) load(list[0].code); }).catch(error => { setMode("error"); setMessage(error instanceof Error ? error.message : "無法取得鄉鎮清單"); }); return () => current.abort(); }, [forced, load]);
  useEffect(() => { if (forced) return; const refresh = () => { if (town) load(town); }; const timer = window.setTimeout(refresh, untilNextTaipeiMidnight()); const visible = () => { if (document.visibilityState === "visible") refresh(); }; addEventListener("focus", refresh); document.addEventListener("visibilitychange", visible); return () => { clearTimeout(timer); removeEventListener("focus", refresh); document.removeEventListener("visibilitychange", visible); }; }, [forced, town, load]);
  const day = data?.forecast.days.find(value => value.date === data.forecast.target_date); const warning = data?.forecast.warnings?.[0]; const selector = <Selector town={town} towns={towns} disabled={mode === "loading" || mode === "cold"} onChange={code => { setTown(code); load(code); }} />; const advice = data?.ai_summary.text || day?.advice_hint || "暫無行程建議。";
  return <main className={compact ? "mini compact" : "mini"}>{!compact && <header><p className="eyebrow">TRIP WEATHER PLANNER</p><h1>Weather preview</h1><p>一張為旅程準備的台灣天氣明信片。</p></header>}{!compact && selector}<p className="status" aria-live="polite">{mode === "loading" ? "正在取得天氣…" : mode === "cold" ? "服務可能正在喚醒，請稍候…" : ""}</p>{(mode === "loading" || mode === "cold") && <section className="card skeleton" aria-label="載入中" />}{(mode === "error" || mode === "empty") && <section className="notice" role="alert"><h2>{mode === "empty" ? "目前沒有可顯示的預報" : "暫時無法取得預報"}</h2><p>{message || "請稍後再試。"}</p><button onClick={() => town && load(town)}>Retry Live Data</button><button className="secondary" onClick={() => load(town || demoTowns[0].code, true)}>Use Demo Data</button></section>}{data && day && <section className="card weather-card">{compact && selector}<div className="card-top"><div>{!compact && <p className="eyebrow">{data.forecast.town.city} · {data.forecast.town.name}</p>}<h2>{compact ? "今日天氣" : `${data.forecast.target_date} Today`}</h2></div><span className="badge">{mode === "demo" ? "Demo" : "Live"}</span></div>{mode === "demo" && <p className="demo-copy">目前顯示範例資料，不是即時天氣。</p>}<div className="weather"><strong>{day.weather || "資料不足"}</strong><span>{day.temp_low_c ?? "—"}° / {day.temp_high_c ?? "—"}°</span><span>降雨 {day.max_pop_percent ?? "—"}%</span></div><div className="signals">{warning && <span className="signal warning">⚠ {data.forecast.warnings?.length} 則警特報：{warning.title}</span>}<span className="signal aqi">AQI {data.forecast.aqi?.value ?? "—"} · {data.forecast.aqi?.level ?? "暫無資料"}</span>{data.forecast.uv && <span className="signal uv">UV {data.forecast.uv.value ?? "—"} · {data.forecast.uv.level ?? "暫無資料"}</span>}</div><p className="advice" title={advice}>{advice}</p>{compact ? <small className="compact-updated">{mode === "demo" ? "Demo" : "Live"} · {new Intl.DateTimeFormat("zh-TW", { timeZone: "Asia/Taipei", month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(data.forecast.generated_at))} 更新</small> : <small>Last updated: {data.forecast.generated_at} · source: {data.forecast.source_dataset}</small>}</section>}{data && day && !compact && <section className="strip" aria-label="未來七日預報">{nextDays().map(date => { const item = data.forecast.days.find(value => value.date === date); return <article key={date}><b>{date.slice(5)}</b><span>{item?.weather || "—"}</span><span>{item?.temp_low_c ?? "—"}–{item?.temp_high_c ?? "—"}°</span></article>; })}</section>}{compact ? <a className="cta compact-cta" href={compactUrl} target="_top">查看完整天氣預覽 →</a> : <a className="cta" href={fullUrl} target="_blank" rel="noopener noreferrer">Open Full Planner — Azure v1.0.0 Phase 1 legacy demo</a>}</main>;
}
